### PR TITLE
Replace ReactRender with IsReactElement

### LINKED ISSUE #131: Can't use different `ReactRender` types in render
The polymorphism over `render` with `ReactRender` lets you use different return types, but it's fixed for the class, which means you can't return different types on different ticks of render. I should be able to return a `String` in one render tick, and a `ReactElement` in another tick. The correct type I think would be:

```purescript
{ ... render :: forall r. ReactRender r. ReactThis props state => Eff ... r }
```

Edit: This is actually wrong, since it means render can't fix the type.
But this higher-ranked type is problematic. I think instead we should just define coercions to `ReactElement`, since these can actually be used _anywhere_ and not just the root of a render.

```purescript
fromString :: String -> ReactElement
fromInt :: Int -> ReactElement
fromNumber :: Number -> ReactElement
fromArray :: Array ReactElement -> ReactElement
```

### PR DESCRIPTION
**Pull request by natefaubion**
Fixes #131 #127

### CODE REVIEW

**Comment by ethul** [comment]
Looks great! Thanks for this update.

Just out of curiosity, should `fragment` be exported as well as `fragmentWithKey`?

**Comment by natefaubion** [comment]
I did not export `fragment` because that's what `toElement [ ... ]` is. I don't think there is a reason to expose the ReactClass directly.

**Comment by paulyoung** [comment]
Perhaps this would help with discoverability.

```purescript
fragment :: Array ReactElement -> ReactElement
fragment = toElement
```

Not being able to find `fragment` led to someone using `fragmentWithKey` instead, and I eventually found this thread.

**Comment by ethul** [comment]
I can see this being handy to match up with `React.Fragment` in JS. However, I am open to opinions on this. If we all think this would be helpful, @paulyoung can you please open a new issue for this? Thanks!

**Pull request merged**
