### PR TITLE
Add @ethul as maintainer

### PR DESCRIPTION
**Pull request by paf31**
@ethul What do you think? I figure you've been acting as maintainer quite a bit more than me lately, so we may as well make it official.

No pressure if you'd rather not, of course.

### CODE REVIEW

**Comment by ethul** [comment]
I am certainly happy to maintain or co-maintain, whichever works for me.

**Comment by ethul** [comment]
Looks good!

**Comment by paf31** [comment]
Thanks!

**Comment by ethul** [comment]
Thank you!

**Pull request merged**
