### PR TITLE
Topic/lifecycle methods

### PR DESCRIPTION
**Pull request by ethul**
Some of the [lifecycle methods](https://facebook.github.io/react/docs/component-specs.html#lifecycle-methods) did not pass along the arguments from React. I've added these arguments. I realize this is a breaking change and I am definitely open to discussion. But I thought they might be handy.

### CODE REVIEW

**Comment by paf31** [comment]
They don't, but you can get them with `getState` and `getProps`. This might be better though.

**Comment by ethul** [comment]
I think using `getState` and `getProps` would give a different result in these lifecycle methods.

For example in `componentWillReceiveProps` if you did `getProps`, I think this would yield the current props. But the props passed in as a param would be the next props.

Same goes for the others. For instance, check out the code example for [shouldComponentUpdate](https://facebook.github.io/react/docs/component-specs.html#updating-shouldcomponentupdate).

**Comment by paf31** [comment]
Ah, makes sense.

**Comment by paf31** [comment]
Thanks!

**Comment by ethul** [comment]
Welcome, thank you for the merge!

**Pull request merged**
