### PR TITLE
Topic/react 0.14

### PR DESCRIPTION
**Pull request by ethul**
These changes update the API and reflect the split of react and react-dom that was introduced in version 0.14.

As a result, I have a separate [purescript-react-dom](https://github.com/ethul/purescript-react-dom/tree/topic/implementation) repository set up for the react-dom bindings. Also, I moved out the example to [purescript-react-example](https://github.com/ethul/purescript-react-example/tree/topic/implementation) since it depends on `purescript-react` and `purescript-react-dom`. I'd be happy to move the new repos to `purescript-contrib` if we decide to go ahead with these changes.

One item I wanted to open up for discussion is how react.js is imported in the foreign code. I've added a `require('react')` line to import react, and I have added a `package.json` with react as a `peerDependency` for compatibility tracking. Going this route seemed appropriate given that we are using commonjs as a standard output for purescript. But making this change means tools like wepack and browserify need to be used for the JS assembly. Maybe this is an okay requirement. That being said, maybe we can make a failover during the require statement to add compatibility for react being available globally. I am open to ideas and suggests on this though.

Additionally, if we merge #54, I'd be happy to resolve the conflicts if we decide to go ahead with these changes.

### CODE REVIEW

**Comment by codedmart** [comment]
Just checking the status of this or upgrading to react 0.14 in general? Thanks!

**Comment by ethul** [comment]
@codedmart If the [breaking changes](http://facebook.github.io/react/blog/2015/10/07/react-v0.14.html#breaking-changes) of react 0.14 don't impact you then I believe you should be able to use react 0.14 with the purescript-react bindings at version 0.5.0. However, without the changes in this PR and `purescript-react-dom` there would not be bindings for stateless classes and bindings to `react-dom`.

@paf31 Do you think this PR looks okay to be merged? I am definitely open to suggestions and discussion on any of these changes.

**Comment by paf31** [comment]
I'm playing catch-up on PRs this week after a vacation, but I'll get to this soon...

**Comment by ethul** [comment]
Thanks @paf31!

**Comment by nwolverson** [comment]
Loving the change to use the npm `react`. Though I did struggle with the require path setup before reading the example.

**Comment by ethul** [comment]
@paf31 I know you mentioned you're catching up on PRs, but I wanted to ping you on #54 and #56. If you think they look okay, and if it helps, I'd be happy to do the merge and make a release (I'd just need repo access).

**Comment by paf31** [comment]
@ethul Yes, very sorry about the delay. This email has been in my inbox for weeks now :disappointed: 

If you're willing, I was going to ask you if you'd like to be maintainer or co-maintainer on `-react` anyway, since I really don't use React very much any more.

**Comment by ethul** [comment]
No problem. I am happy to help maintain. I can merge these this weekend if
you think the PRs are okay.

**Comment by paf31** [comment]
@ethul You should have full access to the repo now. The PR looks good to me, but I haven't spent any time with React 0.14 yet, so I'm not fully sure. If you say it's good to go, I'm sure it is. :+1: 

Do you think Thermite will need any big changes?

**Comment by nwolverson** [comment]
I think it looks good, spent a little while using it and no issues.

**Comment by ethul** [comment]
@paf31 Thanks for the repo access. I will double-check on what changes might be necessary for Thermite.

@nwolverson Thanks for testing it out. Good to know.

**Comment by ethul** [comment]
@paf31 Thermite compiles with no changes. I think the only breaking change is that `purescript-react` now requires react with a require statement. Instead of assuming it is available as a global. So Thermite users will have to ensure that this works for their setup.

**Comment by ethul** [comment]
@paf31 Also, the Thermite example may need an update since `render` is now in [purescript-react-dom](https://github.com/ethul/purescript-react-dom).

PS - Do you think moving `purescript-react-dom` to `purescript-contrib` makes sense?

**Comment by paf31** [comment]
Ok, sounds good. Thanks very much for working on this.

When you're happy, could you please make a release? I was planning to work on Thermite today anyway, so I'll update it to be compatible.

**Comment by ethul** [comment]
Great. And very welcome.

I will make a release of everything, but I might not get it out until
tonight (EST).

**Pull request merged**
