### PR TITLE
fix #107: export childrenToArray and Children type

### LINKED ISSUE #107: export `childrenToArray`
In a library I created a functional react component which has access to context, and I need to use `childrenToArray` (https://github.com/coot/purescript-react-redox/blob/master/src/React/Redox.purs#L223). Would it be fine to export it.

I found a way to use `createClassStateless` but in a dynamic way which forces re-mounts.

### PR DESCRIPTION
**Pull request by coot**

### CODE REVIEW

**Comment by ethul** [comment]
Looks good. Thanks! @paf31 Good to merge?

**Comment by ethul** [comment]
@paf31 If this looks good. I can include this and #103 in a minor release.

**Comment by paf31** [comment]
Please do, thanks, and please feel free to merge PRs if you're happy with them. I don't want to hold things up.

**Comment by ethul** [comment]
Will do. And noted on the PRs. Thanks

**Pull request merged**
