### PR TITLE
Updates for React 0.13

### PR DESCRIPTION
**Pull request by ethul**
I've made some updates to make the API compatible with React 0.13.

The `render` functions are now a bit more bare-bones, but I'd be happy to add back some of the convenience functions like `renderToBody`, etc.

Also, the `mkUI` now returns a foreign data type representing a React class. We could make the function return a React factory (which would give us `props -> UI`), but perhaps `mkUIFactory` would be a better name for that behaviour.

These changes are definitely up for discussion. It is a first-attempt at the API. Note that I still have to make updates to the README and the tutorial. I wanted to get thoughts on the API changes first.

PS - I've moved `react` to a dev-dependency. I am wondering if we can allow the end user to be responsible for ensuring react is present. There are some use-cases where bringing in react through bower is unnecessary (e.g., if webpack is being used).

### CODE REVIEW

**Comment by paf31** [comment]
Looks good to me, thanks!

**Comment by paf31** [comment]
Maybe I can reimplement my React Native bindings on top of this too, as well as Thermite.

**Comment by ethul** [comment]
Great! I will update the readme and tutorial accordingly.

**Comment by ethul** [comment]
I've updated the README. But I am wondering if this is still the best spot for a tutorial. Should we keep this?

**Comment by paf31** [comment]
I only kept the tutorial because I was doing the minimum to update for 0.7, but I think you're right and it can be removed now.

**Comment by ethul** [comment]
I've removed the tutorial.

The only other thing I was thinking about was naming. Is it work transitioning to names like `ReactElement` and `ReactClass`, etc., instead of `UI` and `UIClass`?

I am okay with names as they are, but wondered if it might be worth the switch.

**Comment by paf31** [comment]
Yes we should break as many things as we can before the major version bump I guess. I think renaming to `React*` is a worthwhile change.

**Comment by ethul** [comment]
Agreed. I will make the updates to the names accordingly.

**Comment by ethul** [comment]
Rename done. Let me know if there is anything you'd like me to incorporate into this PR.

Thanks!

**Comment by paf31** [comment]
:100: Thanks!

**Comment by ethul** [comment]
Thank you!

**Pull request merged**
