### PR TITLE
Create LICENSE file

### LINKED ISSUE #97: Add LICENSE file
I noticed this repo has never had a LICENSE file which is ... not ideal. Since this package appears as a dependency of several others, I think it's important for it to have a clear license.

The line `"license": "MIT"` was added to `bower.json` fairly early on (commit [e36352cb21a](https://github.com/purescript-contrib/purescript-react/commit/e36352cb21af42346d2898548f1866d1091ca0ea)), which I interpret to mean that this library has been MIT-licensed implicitly since then. I suggest we adopt the MIT license with a copyright notice assigning copyright to "the purescript-react contributors" or something along those lines.

cc @andreypopp @joneshf @ethul Does that sound good?

### PR DESCRIPTION
**Pull request by paf31**
Closes #97

@ethul @andreypopp @joneshf Does the attribution in particular look good?

### CODE REVIEW

**Comment by ethul** [comment]
I think it looks good; however, would something like "PureScript Contrib"
make sense?

**Comment by paf31** [comment]
I would actually prefer to assign copyright by name to everyone involved, so it's completely clear, but those names would probably have to go in a separate file since there are a few at this point.

**Comment by ethul** [comment]
Okay. Sounds good.

**Comment by paf31** [comment]
@andreypopp What do you think?

**Comment by andreypopp** [comment]
Sorry for not replying earlier. I have no concerns. The MIT license is what I intended actually.

**Comment by paf31** [comment]
Thanks everyone!

**Pull request merged**
