### PR TITLE
Events

### LINKED ISSUE #85: Missing event type for form events and `target` property in other event types
It would be nice if the event types were all mapped to PS types instead of using `unsafeCoerce`. Maybe the types defined in http://www.alexmingoia.com/purescript-pux/docs/API/Pux/Html/Events.html could be used.

### LINKED ISSUE #135: How do I `preventDefault` inside `onKeyUp`?
I don't have `Event` in this handler to do so.

### LINKED ISSUE #136: Revamp events
Before the next major release, I was thinking of looking into options to update the way events are represented to tackle some issues brought up regarding events: #135, #85.

One option suggested in https://github.com/purescript-contrib/purescript-react/issues/135#issuecomment-368241462 could be a good way to go for this.

Thoughts and ideas on this are welcome!

/cc @natefaubion

### PR DESCRIPTION
**Pull request by ethul**
Initial work for updating the representation of events. This is still a work in progress, but putting up what I have so far.

Resolves #85 
Resolves #135 
Resolves #136 

@natefaubion @unclechu @arthurxavierx - Any feedback is most welcome.

### CODE REVIEW

**Comment by ethul** [comment]
Good points. Maybe the alternative to go the type class direction (https://github.com/purescript-contrib/purescript-react/issues/136#issuecomment-378685611) would be safer. I would definitely be open to writing this that way. What do you think?

**Comment by natefaubion** [comment]
I think row types are a fine fit, but treating it as a record is not safe for two reasons:

  * A `SyntheticEvent` is not immutable before calling `persist` due to event pooling
  * Something that is not actually a `Record` should not be typed as `Record`. This is often convenient but breaks down when you use any `Record` operations for updates, merges, etc.

I think you could possibly provide an opaque `newtype` indexed by fields and provide a general `SProxy` based getter that works over `Eff`, with partial applications.

**Comment by ethul** [comment]
Thanks. Along these lines sounds good. I was testing out the following. Is this kind of like what you are suggesting?

```purescript
foreign import data SyntheticEvent_ :: # Type -> Type

type SyntheticEventRow r
  = ( bubbles :: Boolean
    , cancelable :: Boolean
    , currentTarget :: NativeEventTarget
    , defaultPrevented :: Boolean
    , eventPhase :: Number
    , isTrusted :: Boolean
    , nativeEvent :: NativeEvent
    , target :: NativeEventTarget
    , timeStamp :: Number
    , type :: String
    | r
    )

type SyntheticUIEventRow r
  = ( detail :: Number
    , view :: NativeAbstractView
    | r
    )

get
  :: forall eff l r s a
   . RowCons l a r s
  => IsSymbol l
  => SProxy l
  -> SyntheticEvent_ s
  -> Eff eff a
get l r = unsafeGet (reflectSymbol l) r

foreign import unsafeGet :: forall eff r a. String -> SyntheticEvent_ r -> Eff eff a

type SyntheticEvent'' r = SyntheticEvent_ (SyntheticEventRow r)

type SyntheticUIEvent'' = SyntheticEvent_ (SyntheticUIEventRow (SyntheticEventRow ()))

bubbles :: forall eff r. SyntheticEvent'' r -> Eff eff Boolean
bubbles = get (SProxy :: SProxy "bubbles")

detail :: forall eff. SyntheticUIEvent'' -> Eff eff Number
detail = get (SProxy :: SProxy "detail")
```

**Comment by natefaubion** [comment]
Yes, exactly.

**Comment by ethul** [comment]
Great! I will send a PR for this, probably tomorrow.

**Pull request merged**
