### PR TITLE
createClassStateless - add displayName argument

### PR DESCRIPTION
**Pull request by coot**

### CODE REVIEW

**Comment by coot** [comment]
Having `displayName` is really nice for debugging, but also some libraries require it (e.g. `Enzyme`).

**Comment by ethul** [comment]
Is there any chance the `displayName` can be inferred?

https://github.com/facebook/react/issues/10060#issuecomment-311641791

**Comment by coot** [comment]
I am surprised it can! From the `name` attribute, even though PureScript is
using anonymous functions but at least firefox && chrome are using the initial
binding name given by var, let or const.

**Comment by coot** [comment]
I will add this to react-16 PR.

**Pull request closed without merging**
