### PR TITLE
Read/write refs on this

### LINKED ISSUE #123: Refs object is not extensible
Writing a ref causes:
```javascript
Uncaught TypeError: Cannot add property <a>, object is not extensible
```

I believe that refs is a frozen object now.  Related issue facebook/react#7136.

To fix this, I propose that we just write the refs directly to `this` as suggested in the linked issue above. I am open to other ideas though.

react@16.0.0
purescript-react@5.0.0

### PR DESCRIPTION
**Pull request by ethul**
Fixes #123 

Proposal to resolve the issue due to the refs object being frozen.

I am open to other ideas on this. Any feedback is most welcome!

@paf31 @coot

### CODE REVIEW

**Comment by paf31** [comment]
👍 If it works, it's good with me!

**Comment by coot** [comment]
It looks good to me too.  Maybe we could type check that one is not overwriting a life cycle method.

**Comment by ethul** [comment]
Thanks for taking a look!

It turns out that react will still write a ref to `this.refs` when the `ref` prop is used (i.e., when passing a string to name the ref). I've reverted the change to `getRefs` so that `this.refs` is still accessible. Would adding some documentation on this be the best way to go?

@coot I think doing a check is a good call. Are you suggesting to check directly in the JS?

**Comment by ethul** [comment]
Gotcha. I am wondering if maybe releasing this change as a patch release could be done first. Then we can introduce the type change as a separate PR as a breaking change?

**Comment by coot** [comment]
Yes, I think that's fine.

**Pull request merged**
