### PR TITLE
Renamed `renderComponent` to `render` to match new React API

### PR DESCRIPTION
**Pull request by spicydonuts**

### CODE REVIEW

**Comment by spicydonuts** [comment]
Might want to update React to `0.13.x` as well.

**Comment by spicydonuts** [comment]
I'll probably have to look over other breaking API changes in 13 and test some more things.  Getting a warning about not putting a key on a list of components, but I'm only rendering two non-list components in my test.

**Comment by paf31** [comment]
I'd like to update to 0.13 but I had some issue last time I tried. I'll spend a bit of time with this before merging, so that I can review properly. Thanks!

**Comment by ethul** [comment]
Closing because `render` now exists in [purescript-react-dom](https://github.com/purescript-contrib/purescript-react-dom).

**Pull request closed without merging**
